<?php

  $locale = 'el_gr';

  $el_gr = [
		'Test'  => 'Δοκιμή',
		'Username'=>'Όνομα χρήστη',
		'Password'=>'Κωδικός',
    'USERNAME'=>'ΟΝΟΜΑ ΧΡΗΣΤΗ',
    'PASSWORD'=>'ΚΩΔΙΚΟΣ',
    'LANGUAGE'=>'ΓΛΩΣΣΑ',
    'SIGN IN'=>'ΕΙΣΟΔΟΣ',
    'SIGN UP'=>'ΕΓΓΡΑΦΗ',
		'City'=>'Πόλη',
    'Create'=>'Δημιουργία',
    'Delete'=>'Διαγραφή',
    'Save'=>'Αποθήκευση',
    'Products'=>'Προϊόντα',
    'Customers'=>'Πελάτες',
    'Stores'=>'Καταστήματα',
    'Card Levels'=>'Επίπεδα Καρτών',
    'Achievements'=>'Πρόοδος',
    'Transactions'=>'Συναλλαγές',
    'Devices'=>'Συσκευές',
    'Dashboard'=>'Πάνελ Διαχείρισης',
    'Credits'=>'Πόντοι',
    'Statistics'=>'Στατιστικά',
    'Admin'=>'Διαχειριστής',
    'Admin Dashboard'=>'Πάνελ Διαχειριστή',
    'First Name'=>'Όνομα',
    'Last Name'=>'Επίθετο',
    'Phone'=>'Τηλέφωνο',
    'Mobile Phone'=>'Κινητό Τηλέφωνο',
    'Card'=>'Κάρτα',
    'Home Phone'=>'Τηλέφωνο Κατοικίας',
    'Primary Email'=>'Πρωταρχικό Email',
    'Secondary Email'=>'Δευτερεύον Email',
    'Level'=>'Επίπεδο',
    'View Transactions'=>'Εμφάνιση Συναλλαγών',
    'Credits'=>'Πόντοι',
    'Send SMS Marketing'=>'Αποστολή Καμπάνιας SMS',
    'Sens Email Marketing'=>'Αποστολή Καμπάνιας Email',
    'Address'=>'Διεύθυνση',
    'Postal Code'=>'Ταχυδρομικός Κώδικας',
    'Country'=>'Χώρα',
    'Card Level'=>'Επίπεδο Κάρτας',
    'Registration'=>'Εγγραφή',
    'Back'=>'Πίσω',
    'Title'=>'Τίτλος',
    'SMS Marketing'=>'Καμπάνια SMS',
    'Execution Date'=>'Ημερομηνία Εκτέλεσης',
    'Execution Time'=>'Ώρα Εκτέλεσης',
    'Request Date'=>'Ημερομηνία Αιτήματος',
    'Request Time'=>'Ωρα Αιτήματος',
    'Customer'=>'Πελάτης',
    'Store'=>'Κατάστημα',
    'Achievement'=>'Πρόοδος',
    'Transaction'=>'Συναλλαγή',
    'Device'=>'Συσκευή',
    'Product'=>'Προϊόν',
    'Code'=>'Κωδικός',
    'Description'=>'Περιγραφή',
    'Logout'=>'Έξοδος',
    'Enabled'=>'Ενεργοποιημένο',
    'Login'=>'Είσοδος',
    'Help: To create a new Credits listing, click on the \'View Credits\' button, in the page of the product you want the offer to be created for.'=>'Βοήθεια: Για να δημιουργήσετε νέες προσφορές πόντων, πατήστε το κουμπί \'Εμφάνιση Πόντων\' στη σελίδα του προϊόντος για το οποίο δημιουργείτε την προσφορά.',


	];

 ?>
